name: NEWT Starter Kit
headercolor: bg-light
logo: /images/newt_logo.png
alttext: Newt Site Starter Kit
logourl: /
copyright: null
author: Ben Rudolph
footerlogo: null
footerlogoalttext: null
footerlogourl: null
copyurl: null
